/**
 * This file was automatically generated by swagger-extract-definitions.
 * DO NOT MODIFY IT BY HAND.
 */

export type ProductsGetReply = ProductsGetReplyStatus200;

export type ProductsGetReplyStatus200 = Product[];

export type ProductsPostReply = ProductsPostReplyStatus201;

export type ProductsIdPutReply = ProductsIdPutReplyStatus200;

export type ProductsIdDeleteReply = ProductsIdDeleteReplyStatus204;

export interface API {
  '/products': {
    GET: ProductsGet;
    POST: ProductsPost;
  };
  '/products/:id': {
    PUT: ProductsIdPut;
    DELETE: ProductsIdDelete;
  };
}

export interface ProductsGet {
  Querystring: ProductsGetQuerystring;
  Reply: ProductsGetReply;
}

export interface ProductsGetQuerystring {
  limit: number;
}

export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: Rating;
  [k: string]: unknown;
}

export interface Rating {
  rate: number;
  count: number;
  [k: string]: unknown;
}

export interface ProductsPost {
  Body: ProductsPostBody;
  Reply: ProductsPostReply;
}

export interface ProductsPostBody {
  title: string;
  description: string;
  price: number;
  category: string;
  image: string;
  rating: {
    rate?: number;
    count?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

export interface ProductsPostReplyStatus201 {
  [k: string]: unknown;
}

export interface ProductsIdPut {
  Body: ProductsIdPutBody;
  Params: ProductsIdPutParams;
  Reply: ProductsIdPutReply;
}

export interface ProductsIdPutBody {
  title?: string;
  description?: string;
  price?: number;
  category?: string;
  image?: string;
  rating?: {
    rate?: number;
    count?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

export interface ProductsIdPutParams {
  id: number;
}

export interface ProductsIdPutReplyStatus200 {
  [k: string]: unknown;
}

export interface ProductsIdDelete {
  Params: ProductsIdDeleteParams;
  Reply: ProductsIdDeleteReply;
}

export interface ProductsIdDeleteParams {
  id: number;
}

export interface ProductsIdDeleteReplyStatus204 {
  [k: string]: unknown;
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "Product".
 */
export interface Product1 {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: Rating;
  [k: string]: unknown;
}

/**
 * This interface was referenced by `API`'s JSON-Schema
 * via the `definition` "Rating".
 */
export interface Rating1 {
  rate: number;
  count: number;
  [k: string]: unknown;
}
