/**
 * This file was automatically generated by swagger-extract-definitions.
 * DO NOT MODIFY IT BY HAND.
 */

export type ProductsGetReply = ProductsGetReplyStatus200;

export type ProductsGetReplyStatus200 = Product[];

export type ProductsPostReply = Ok | Error;

export type ProductsIdPutReply = Ok | Error;

export type ProductsIdDeleteReply = Ok | Error;

export interface PRODUCTS_API {
  '/products': {
    GET: ProductsGet;
    POST: ProductsPost;
  };
  '/products/:id': {
    PUT: ProductsIdPut;
    DELETE: ProductsIdDelete;
  };
}

export interface ProductsGet {
  Querystring: ProductsGetQuerystring;
  Reply: ProductsGetReply;
}

export interface ProductsGetQuerystring {
  limit: number;
}

export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: Rating;
}

export interface Rating {
  rate: number;
  count: number;
}

export interface ProductsPost {
  Body: ProductsPostBody;
  Reply: ProductsPostReply;
}

export interface ProductsPostBody {
  title: string;
  description: string;
  price: number;
  category: string;
  image: string;
  rating: {
    rate?: number;
    count?: number;
  };
}

export interface Ok {
  status: string;
}

/**
 * Error response
 */
export interface Error {
  error: string;
  message?: string;
}

export interface ProductsIdPut {
  Body: ProductsIdPutBody;
  Params: ProductsIdPutParams;
  Reply: ProductsIdPutReply;
}

export interface ProductsIdPutBody {
  title?: string;
  description?: string;
  price?: number;
  category?: string;
  image?: string;
  rating?: {
    rate?: number;
    count?: number;
  };
}

export interface ProductsIdPutParams {
  id: number;
}

export interface ProductsIdDelete {
  Params: ProductsIdDeleteParams;
  Reply: ProductsIdDeleteReply;
}

export interface ProductsIdDeleteParams {
  id: number;
}
